spring.application.name=food

spring.datasource.url=jdbc:postgresql://localhost:5432/TestSixthMarch
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345678909

server.port=8082
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false

app.jwt.secret=FoodAppJwtSecretKeyChangeMeToSomethingLongAndRandom1234567890
app.jwt.issuer=food-app
app.jwt.expiration-minutes=240

app.bootstrap.system-admin-full-name=System Admin
app.bootstrap.system-admin-email=admin@gmail.com
app.bootstrap.system-admin-password=admin

